version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - psql:/var/lib/postgresql/data
  drupal:
    image: drupal
    ports:
      - "8080:80" 
    depends_on:
      - db
volumes:
  psql: